/**
 * LearningInsight — personalised recommendations generated by the Insight Engine.
 * Collection: /tenants/{tenantId}/insights/{insightId}
 * @module progress/insight
 */

import type { FirestoreTimestamp } from "../identity/user";

export type InsightType =
  | "weak_topic_recommendation"
  | "exam_preparation"
  | "streak_encouragement"
  | "improvement_celebration"
  | "at_risk_intervention"
  | "cross_system_correlation";

export type InsightActionType = "practice_space" | "review_exam" | "seek_help" | "celebrate";

export type InsightPriority = "high" | "medium" | "low";

export interface LearningInsight {
  id: string;
  tenantId: string;
  studentId: string;
  type: InsightType;
  priority: InsightPriority;
  title: string;
  description: string;
  actionType: InsightActionType;
  actionEntityId?: string;
  actionEntityTitle?: string;
  createdAt: FirestoreTimestamp;
  dismissedAt?: FirestoreTimestamp;
}
