/**
 * `learningInsightRepo` (SDK-LAYERS-PLAN §4.1, domain plan §Repositories).
 *
 * Read + dismiss for the personalised `LearningInsight` stream (generated by the
 * analytics insight engine; this domain exposes the learner-facing read/dismiss).
 *   • `list(filter)` paginates via opaque cursor.
 *   • `dismiss(insightId)` → `dismissInsight` (optimistic allow-list ✅ — the
 *     query layer owns the optimistic patch; the repo just issues the call).
 *   • `groupByPriority(insights)` derived (computed once).
 *
 * Per-entity repo — `api` + `@levelup/domain` only; never a sibling repo (R6).
 */
import type { InsightId, InsightPriority, LearningInsight } from "@levelup/domain";
import type {
  ApiClient,
  DismissInsightResponse,
  ListLearningInsightsRequest,
  PageResponse,
} from "./api-types.js";
import { listOnce, paginate, type PageBag } from "./paginate.js";

export type InsightsByPriority = Record<InsightPriority, LearningInsight[]>;

export interface LearningInsightRepo {
  list(filter: ListLearningInsightsRequest): Promise<PageResponse<LearningInsight>>;
  paginate(filter: ListLearningInsightsRequest): Promise<PageBag<LearningInsight>>;
  recordDismissal(insightId: InsightId): Promise<DismissInsightResponse>;
  computeByPriority(insights: readonly LearningInsight[]): InsightsByPriority;
}

export function createLearningInsightRepo(api: ApiClient): LearningInsightRepo {
  return {
    list: (filter) => listOnce((req) => api.levelup.listLearningInsights(req), filter),
    paginate: (filter) => paginate((req) => api.levelup.listLearningInsights(req), filter),
    recordDismissal: (insightId) => api.levelup.dismissInsight({ insightId }),
    computeByPriority: (insights) => {
      const out = {} as InsightsByPriority;
      for (const insight of insights) {
        (out[insight.priority] ??= []).push(insight);
      }
      return out;
    },
  };
}
