#!/usr/bin/env node
/**
 * Generates tokens.css and bridge.css from tokens.cjs (the SSOT).
 * Run from anywhere: node packages/lyceum-preset/scripts/generate-css.cjs
 */
const fs = require("fs");
const path = require("path");
const { primitives, semantic, bridge, staticTokens, hexToHslTriplet, resolve } =
  require("../tokens.cjs");

const pkgRoot = path.join(__dirname, "..");
const HEADER = (what) =>
  `/* GENERATED by scripts/generate-css.cjs from tokens.cjs — DO NOT EDIT BY HAND.\n * ${what}\n * Source of truth: 00-FOUNDATION.md §2–§4 (Lyceum, "Modern Scholarly").\n */\n`;

/* ── tokens.css ──────────────────────────────────────────────────────── */
function emitPrimitives() {
  return Object.entries(primitives)
    .map(([k, v]) => `  --${k}: ${v};`)
    .join("\n");
}

function emitSemantic(mode) {
  return Object.entries(semantic[mode])
    .map(([k, prim]) => `  --${k}: var(--${prim});`)
    .join("\n");
}

function emitTwins(mode) {
  return Object.entries(semantic[mode])
    .map(([k, prim]) => `  --ly-${k}: ${hexToHslTriplet(resolve(prim))};`)
    .join("\n");
}

const tokensCss = `${HEADER("Lyceum custom properties: primitives + semantic roles + HSL twins (--ly-*).")}
:root {
  /* 1. Primitives (§2.1) — never use directly in app code; semantic only. */
${emitPrimitives()}

  /* 2. Semantic roles (§2.2) + domain scales (§2.3) — components use THESE. */
${emitSemantic("light")}

  /* 3. Non-color scales (§3–§4). */
${staticTokens.replace(/^\n|\n$/g, "")}

  /* 4. HSL triplet twins of the semantic set, consumed by preset.cjs as
     hsl(var(--ly-*) / <alpha-value>) so Tailwind opacity modifiers work. */
${emitTwins("light")}
}

/* Dark theme — only semantic roles flip (primitives stay). Both the app
   convention (class .dark via next-themes) and the Lyceum prototype
   convention ([data-theme="dark"]) are honored. */
.dark,
[data-theme="dark"] {
${emitSemantic("dark")}

${emitTwins("dark")}
}
`;

/* ── bridge.css ──────────────────────────────────────────────────────── */
function emitBridge(mode) {
  return Object.entries(bridge[mode])
    .map(([k, prim]) => `  --${k}: ${hexToHslTriplet(resolve(prim))};`)
    .join("\n");
}

const bridgeCss = `${HEADER("shadcn/@levelup-tailwind-config variable override — repaints every shared-ui component in Lyceum.")}
/* Import AFTER '@levelup/tailwind-config/variables.css'.
 *
 * Deliberately UNLAYERED (variables.css declares inside @layer base, and
 * unlayered declarations win over layered ones) so this file always takes
 * precedence regardless of bundling order quirks.
 *
 * :not(.high-contrast) keeps the existing accessibility high-contrast
 * modes (.high-contrast / .dark.high-contrast in variables.css) fully
 * functional: when high-contrast is active this bridge steps aside.
 */
:root:not(.high-contrast) {
${emitBridge("light")}
  --radius: 0.875rem; /* Lyceum radius-lg 14px → shadcn rounded-lg; md/sm derive -2/-4px */
}

.dark:not(.high-contrast) {
${emitBridge("dark")}
}
`;

fs.writeFileSync(path.join(pkgRoot, "tokens.css"), tokensCss);
fs.writeFileSync(path.join(pkgRoot, "bridge.css"), bridgeCss);
console.log("wrote tokens.css and bridge.css");
