/**
 * LevelUp Cloud Functions type surface (U3.2, MIGRATION-PATTERN.md).
 *
 * Vocabulary (enums, grading-type constants) comes from @levelup/domain —
 * verified value-identical to the retired shared-types definitions 2026-07-04.
 * Doc shapes come from ../contracts/legacy-docs — honest LOCAL types for what
 * is actually at rest in the unprefixed collections (NOT domain entities).
 * Wire request schemas live in ../contracts/wire.
 */

// ─── Vocabulary from @levelup/domain ─────────────────────────────────────────
export { AUTO_EVALUATABLE_TYPES, AI_EVALUATABLE_TYPES } from "@levelup/domain";

export type {
  ItemType,
  QuestionType,
  MaterialType,
  BloomsLevel,
  SpaceType,
  SpaceStatus,
  SpaceAccessType,
  StoryPointType,
  AgentType,
  ChatMessageRole,
  TestSessionStatus,
  TestSessionType,
  QuestionStatus,
  ProgressStatus,
  RubricScoringMode,
  RubricPresetCategory,
} from "@levelup/domain";

// ─── Legacy doc shapes (local, honest) ───────────────────────────────────────
export type {
  LegacyTimestamp,
  LegacyStoryPointTypeField,
  // Rubric + evaluation
  RubricCriterionLevel,
  RubricCriterion,
  EvaluationDimension,
  UnifiedRubric,
  FeedbackItem,
  RubricBreakdownItem,
  UnifiedEvaluationResult,
  // Item metadata + payloads
  PyqInfo,
  MigrationSource,
  ItemMetadata,
  ItemAnalytics,
  MCQOption,
  MCQData,
  MCAQData,
  TrueFalseData,
  NumericalData,
  TextData,
  ParagraphData,
  CodeTestCase,
  CodeData,
  FillBlank,
  FillBlanksData,
  FillBlanksDDOption,
  FillBlanksDDBlank,
  FillBlanksDDData,
  MatchingPair,
  MatchingData,
  JumbledItem,
  JumbledData,
  AudioData,
  ImageEvaluationData,
  GroupOptionsGroup,
  GroupOptionsItem,
  GroupOptionsData,
  ChatAgentQuestionData,
  QuestionTypeData,
  QuestionPayload,
  RichContentBlockItem,
  RichContentBlock,
  MaterialPayload,
  InteractivePayload,
  AssessmentRubricItem,
  AssessmentPayload,
  DiscussionPayload,
  ProjectPayload,
  CheckpointPayload,
  ItemPayload,
  ItemAttachment,
  UnifiedItem,
  // LevelUp docs
  Space,
  SpaceStats,
  SpaceRatingAggregate,
  ContentVersion,
  SpaceReview,
  StoryPoint,
  StoryPointSection,
  AdaptiveConfig,
  AssessmentSchedule,
  RetryConfig,
  AssessmentConfig,
  StoryPointStats,
  Agent,
  EvaluationObjective,
  AnswerKey,
  ChatSession,
  ChatMessage,
  QuestionBankItem,
  QuestionBankFilter,
  DigitalTestSession,
  TestSubmission,
  TestAnalytics,
  AnalyticsBreakdownEntry,
  AdaptiveState,
  // Progress
  QuestionProgressData,
  StoredEvaluation,
  AttemptRecord,
  ItemProgressEntry,
  StoryPointProgress,
  StoryPointProgressDoc,
  SpaceProgress,
  RubricPreset,
  UserMembership,
  TenantRole,
} from "../contracts/legacy-docs";
